name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # container: 
    container:
      image: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - name: Packages
        run: apt-get --allow-unauthenticated update && apt-get install -y gcc-multilib g++-multilib python3 python3-pip cmake
      - name: Pip
        run: pip install meson robotpy robotpy-build
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Sync python
        run: cd pybot && robotpy sync
        env:
          GENERATE_EMPTY_DRIVE_TRAJECTORIES: true
      - name: Test python
        run: echo TODO
