name: Meson

on:
  push:
  pull_request:

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: Packages
        run: apt-get --allow-unauthenticated update && apt-get install -y build-essential python3 python3-pip git gcc-multilib g++-multilib python3 python3-pip cmake && pip3 install meson
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup
        run: meson setup build
      - name: Compile
        run: meson compile -C build -j4
      - name: Test
        run: meson test -C build
